/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ROY (https://sketchfab.com/roy.gearloft.in)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/dry-thin-grass-43f57bef322c4f4597428d290b498764
title: Dry Thin Grass
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dry_thin_grass-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.33}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.carpet} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.carpet} />
            <mesh geometry={nodes.Object_6.geometry} material={materials.carpet} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.carpet} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.carpet} />
            <mesh geometry={nodes.Object_9.geometry} material={materials['1___Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dry_thin_grass-transformed.glb')
